### ISSUE TITLE
Grad-Cam issue

### ISSUE THREAD

**Issue by Annieliaquat** [shucheng-liu/TensorFlow_CAM#1]
I have used SSD MobileNetV2 FPNLite 320x320 from Tensorflow model zoo. How can I use your github to generate Grad-Cam for my dataset. plz plz plz help me in this regards.

**Comment by Annieliaquat** [comment]
Please I literally need the answer for my question, because it has been days I am trying to find the Grad-Cam classification but am failing

**Comment by shucheng-liu** [comment]
Unfortunately, this project is designed specifically for classification models.
For object detection models, it definitely requires extra works, because a lot of processing steps on bounding boxes are not differentiable (Grad-CAM needs gradient values), and we can't even determine which feature map a bounding box comes from without tracking it.

You may try some gradient-free methods such as AblationCAM and EigenCAM.
